### ISSUE TITLE
Chinese map function

### ISSUE THREAD

**Issue by sammo3182** [sammo3182/drhutools#5]
Create a function to draw dots or polygons in a Chinese map. 

1. Functionalize the following codes
2. Enable drawing points and polygons in the map
3. Enable drawing maps for different levels of unit (city, province)

e.g., 

`goodChinaMap(data = XXXX, unit = c("city", "province"), shape = c("points", "polygons"), saveDir = "XXX", ...)`

Reference code

```r
p_load(
  leaflet,
  leafletCN,
  htmlwidgets,
  webshot2, 
  regioncode
)
  
# background ---------------------------------------------------------------------

plot_prov <- data.frame( # has to be a data.frame rather than tibble or other classes
  name = regionNames("china")
)

plot_prov <- cgss1021 |> 
  filter(year == 2010) |> 
  select(prov, mandarinSpeak, mandarinListen) |> 
  group_by(prov) |> 
  summarise(value_speak = mean(mandarinSpeak, na.rm = TRUE),
         value_listen = mean(mandarinListen, na.rm = TRUE)) |> 
  ungroup() |> 
  right_join(plot_prov, by = c("prov" = "name"))

plot_prov_speak <- select(plot_prov, prov, value_speak) |> 
  rename(value = value_speak) |> 
  as.data.frame()
plot_prov_listen <- select(plot_prov, prov, value_listen) |> 
  rename(value = value_listen) |> 
  as.data.frame()


# 还有很多其他参数设置，类似 leaflet::leaflet
plot_speak <- geojsonMap(plot_prov_speak, 
           mapName = "china", 
           palette = gb_pal(palette = "main", reverse = TRUE)(2), 
           colorMethod = "bin", 
           legendTitle = "Speaking")

plot_listen <- geojsonMap(plot_prov_listen, 
           mapName = "china", 
           palette = gb_pal(palette = "main", reverse = TRUE)(2), 
           colorMethod = "bin", 
           legendTitle = "Listening")

ls_map <- list(speak = plot_prov_speak, listen = plot_prov_listen) |> 
  map2(c("Speaking", "Listening"),
    \(data, name){
      geojsonMap(data, 
           mapName = "china", 
           palette = gb_pal(palette = "main", reverse = TRUE)(2), 
           colorMethod = "numeric", 
           legendTitle = name,
           domain = range(c(plot_prov_speak$value, plot_prov_listen$value), na.rm = TRUE))
    }
  )

walk2(ls_map, c("speak", "listen"), \(plot, suffix) {
  html_plot <- tempfile(fileext = ".html") # save the html to a temporary file
  
  saveWidget(plot, html_plot, selfcontained = FALSE)
  
  name_file <- paste0("map_", suffix, ".png")
  
  webshot(
    html_plot,
    vheight = 900,
    # high enough to show Indonesia
    expand = c(-170, 0, 0, -100),
    # truncate the unnecessary neighbor countries
    file = here("output", name_file)
  )
})
```

**Comment by WaitingJoyce** [comment]
[Uploading goodchinesemap_0.1.0.tar.gz…]()

**Comment by WaitingJoyce** [comment]
p_load(
  leaflet,
  leafletCN,
  htmlwidgets,
  webshot2, 
  regioncode
  mapview
)
  
# background ---------------------------------------------------------------------

plot_prov <- data.frame( # has to be a data.frame rather than tibble or other classes
  name = regionNames("china")
)

plot_prov <- cgss1021 |> 
  filter(year == 2010) |> 
  select(prov, mandarinSpeak, mandarinListen) |> 
  group_by(prov) |> 
  summarise(value_speak = mean(mandarinSpeak, na.rm = TRUE),
         value_listen = mean(mandarinListen, na.rm = TRUE)) |> 
  ungroup() |> 
  right_join(plot_prov, by = c("prov" = "name"))

plot_prov_speak <- select(plot_prov, prov, value_speak) |> 
  rename(value = value_speak) |> 
  as.data.frame()
plot_prov_listen <- select(plot_prov, prov, value_listen) |> 
  rename(value = value_listen) |> 
  as.data.frame()


# 还有很多其他参数设置，类似 leaflet::leaflet
plot_speak <- geojsonMap(plot_prov_speak, 
           mapName = "china", 
           palette = gb_pal(palette = "main", reverse = TRUE)(2), 
           colorMethod = "bin", 
           legendTitle = "Speaking")

plot_listen <- geojsonMap(plot_prov_listen, 
           mapName = "china", 
           palette = gb_pal(palette = "main", reverse = TRUE)(2), 
           colorMethod = "bin", 
           legendTitle = "Listening")

ls_map <- list(speak = plot_prov_speak, listen = plot_prov_listen) |> 
  map2(c("Speaking", "Listening"),
    \(data, name){
      geojsonMap(data, 
           mapName = "china", 
           palette = gb_pal(palette = "main", reverse = TRUE)(2), 
           colorMethod = "numeric", 
           legendTitle = name,
           domain = range(c(plot_prov_speak$value, plot_prov_listen$value), na.rm = TRUE))
    }
  )

walk2(ls_map, c("speak", "listen"), \(plot, suffix) {
  html_plot <- tempfile(fileext = ".html") # save the html to a temporary file
  
  saveWidget(plot, html_plot, selfcontained = FALSE)
  
  name_file <- paste0("map_", suffix, ".png")
  
  webshot(
    html_plot,
    vheight = 900,
    # high enough to show Indonesia
    expand = c(-170, 0, 0, -100),
    # truncate the unnecessary neighbor countries
    file = here("output", name_file)
  )
})

#Enable drawing points and polygons in the map for different level ()
filePath_province = system.file("geojson/china.json",package = "leafletCN")
china_map_province = read.geoShape(filePath)
filePath_city = system.file("geojson/city.json",package = "leafletCN")
china_map_city = read.geoShape(filePath_city)

polygons_map <- china_map_province[china_map_province$name == "北京市", ]
plots_map <- china_map_city[china_map_city$name == "武汉", ]
city_center <- plots_map@polygons[[1]]@Polygons[[1]]@labpt
lng <- city_center[1]
lat <- city_center[2]
map <- leaflet() |>
  amap() |>
  addPolygons(data = polygons_map, fillColor = "lightblue", stroke = TRUE, color = "blue", weight = 1, fillOpacity = 0.5, label = ~name) |>
  addCircleMarkers(lat = lat, lng = lng, popup = "武汉",
                   radius = 5, color = "red", fillColor = "black", fillOpacity = 0.7)
map
html_plot <- tempfile(fileext = ".html")

name_file <- paste0("map.png")
mapshot(map, file = file.path("output", name_file))

**Comment by sammo3182** [comment]
A couple of issues need to be fixed:

- [x] Remove the `years` argument. It is duplicated with `animate_var`
- [x] Offer users arguments to apply alternative palettes. Replace this function with the `palette` and `reverse_palette`

**Comment by sammo3182** [comment]
@WaitingJoyce Can you add an option for users to customize the legend?

- [ ] Customize the name of the legend
- [ ] Let people to choose to show a numeric or factor in the legend.

For `point`, modify the following line:

https://github.com/sammo3182/drhutools/blob/845e20e001bf5394a21d008358568a9f3ee04bab/R/goodmap.R#L143

For `polygon`, provide an argument to customize the following argument

https://github.com/sammo3182/drhutools/blob/845e20e001bf5394a21d008358568a9f3ee04bab/R/goodmap.R#L218
